baseURL = "https://sad-knuth-e7a56d.netlify.app/"
title = "inteligência das coisas"
theme =  "hugo-theme-cleanwhite"
languageCode = "pt-br"
preserveTaxonomyNames = true
disqusShortname = "inteligenciadascoisas"
enableEmoji = true
googleAnalytics = "UA-165857578-1"

[outputs]
    home = ["HTML"]

[params]
    header_image = "img/home-bg-logo.png"
    SEOTitle = "inteligência das coisas"
    description = "Blog de tecnologia aplicada, com tutoriais e artigos práticos e interativos."
    keyword = "blog, iot, internet das coisas, desenvolvimento, frontend, algoritmos, eletrônica, embarcados, protótipos, visão computacional, automação, design, motion graphics"
    slogan = "blog de tecnologia aplicada"

    logo_svg = "img/logo-idc.svg"

    image_404 = "img/404-bg.jpg"
    title_404 = "Página não encontrada :("
    omit_categories = false

    # Sidebar settings
    mascot_footer = "img/mascot-2.gif"
    mascot = "img/mascot.gif"
    sidebar_about_description = "Pesquisador na HBSIS Ambev, Maker, Desenvolvedor, Ilustrador, Violeiro, Entusiasta Open Source e apaixonado por aprender e compartilhar."
    sidebar_avatar = "img/alexandrealvaro.png"
    featured_tags = true
    featured_condition_size = 1 
    #custom_js = [""]
    
    about_me = true


[params.social]
    rss             = false 
    resume          = "https://alexandremendoncaalvaro.github.io"
    email           = "alexandre.alvaro@hotmail.com"
    facebook        = "https://www.facebook.com/peritto"
    linkedin        = "https://www.linkedin.com/in/alexandre-mendon%C3%A7a-%C3%A1lvaro-273b0050"
    github          = "https://github.com/alexandremendoncaalvaro"
    instagram       = "https://www.instagram.com/alemendalvaro"
    deviantart      = "https://www.deviantart.com/peritto/gallery"
    soundcloud      = "https://soundcloud.com/peritto-1"
    whatsapp        = "https://api.whatsapp.com/send?phone=5547991512508&amp;text=Site"


[markup]
    [markup.tableOfContents]
        endLevel = 2
        startLevel = 1
    [markup.highlight]
        style = "dracula"